services:
  db:
    image: mysql:8.4
    env_file:
      - .env.docker
    container_name: mysql_crud
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d   # 01-schema.sql, 02-seed.sql
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_0900_ai_ci"
      ]
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    container_name: crud_api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    command: ["node", "dist/server.js"]

volumes:
  mysql_data:
