CREATE TABLE persona (
  id BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID(),1)),
  nombre VARCHAR(100) NOT NULL,
  apellidos VARCHAR(100) NOT NULL,
  rut VARCHAR(20) NOT NULL UNIQUE,
  direccion VARCHAR(200),
  celular VARCHAR(20) UNIQUE,
  email VARCHAR(100) UNIQUE,
  fecha_nacimiento DATE NOT NULL,
  fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE empresa (
  id BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID(),1)),
  nombre VARCHAR(100) NOT NULL,
  rut VARCHAR(20) NOT NULL UNIQUE,
  direccion VARCHAR(200),
  celular VARCHAR(20) UNIQUE,
  email VARCHAR(100) UNIQUE,
  fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE persona_empresa (
  id BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID(),1)),
  persona_id BINARY(16) NOT NULL,
  empresa_id BINARY(16) NOT NULL,
  cargo VARCHAR(100),
  area VARCHAR(100),
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE,
  es_actual BOOLEAN DEFAULT TRUE,
  fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (persona_id) REFERENCES persona(id) ON DELETE CASCADE,
  FOREIGN KEY (empresa_id) REFERENCES empresa(id) ON DELETE CASCADE
);
